include: package:very_good_analysis/analysis_options.10.0.0.yaml

analyzer:
  exclude:
    - lib/l10n/gen/*
    - lib/generated_plugin_registrant.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
  errors:
    invalid_annotation_target: ignore
    # TODO: Remove these gradually
    avoid_catches_without_on_clauses: ignore
    document_ignores: ignore
    discarded_futures: ignore

linter:
  rules:
    public_member_api_docs: false
